export default {
    APP_NAME: "Puffin",
    APP_VERSION: "1.0.0",
    ALPHABET: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
    PAGE_SIZE: 20,

    PREFER_FILE: "./data/preferences",
    DATABASE_FILE: "./data/movie.db",
    COVER_HOME: "./data/cover",
    TRANSCODE_HOME: "./data/video",
    PROTECTED_URL: "/metadata",
    INIT_URL: "/init",

    SESSION_TIMEOUT: 30 * 60 * 1000, // 30 minutes
    SESSION_KEY: "SESSID",

    VIDEO_CAPTURE_TIME: 60,
    VIDEO_CHUNK_SIZE: 2 * 10 ** 7, // 20 MB
    VIDEO_FILE_FORMATS: [
        ".3g2",
        ".3gp",
        ".asf",
        ".avi",
        ".dat",
        ".flv",
        ".m2ts",
        ".m4v",
        ".mkv",
        ".mod",
        ".mov",
        ".mp4",
        ".mpeg",
        ".mpg",
        ".mts",
        ".oga",
        ".ogg",
        ".ogv",
        ".qt",
        ".rm",
        ".rmvb",
        ".ts",
        ".vob",
        ".webm",
        ".wmv",
    ],

    REGION: {
        CN: "中国",
        JP: "日本",
        KR: "韩国",
        IN: "印度",
        TH: "泰国",
        US: "美国",
        CA: "加拿大",
        RU: "俄罗斯",
        GB: "英国",
        FR: "法国",
        DE: "德国",
        IT: "意大利",
        ES: "西班牙",
        IE: "爱尔兰",
        SE: "瑞典",
        DK: "丹麦",
        AU: "澳大利亚",
        BR: "巴西",
        AS: "亚洲",
        OC: "欧美",
        OT: "其他",
    },
    QUALITY: {
        "4K": "4K",
        UHD: "超高清",
        FHD: "全高清",
        HD: "高清",
        SD: "标清",
        OT: "其他",
    },
    CENSORSHIP: {
        CENSORED: "有码",
        REDUCED: "消码",
        UNCENSORED: "无码",
    },
    RATING: {
        UNIVERSAL: "普适级",
        GUIDANCE: "指导级",
        RESTRICTED: "限制级",
        ADULT: "成人级",
    },

    METAFIELDS: {
        region: "地区",
        quality: "画质",
        censorship: "审查",
        rating: "分级",
        producer: "制作商",
        director: "导演",
        starring: "主演",
        series: "系列",
        genres: "类型",
    },
};
